### ISSUE TITLE
ring attention with varlen

### ISSUE THREAD

**Issue by Infi-zc** [zhuzilin/ring-flash-attention#1]
Hi, Zilin, I'm curious if there is a design document or a conceptual design available for the solution that supports variable length with ring attention?

**Comment by zhuzilin** [comment]
I'm still thinking about if there is a clean way to write one :joy: The problem is that the communication will be chaotic as the segments on each rank would also be varlen...

**Comment by zhuzilin** [comment]
@Infi-zc The main idea would be writing a complex version of `send_recv_kv` with regard to the global `cu_seqlen`.

**Comment by zhuzilin** [comment]
@Infi-zc Hi! I just implemented the `ring_flash_attn_varlen_qkvpacked_func`, maybe this will suits your need?
