### ISSUE TITLE
Is there a FlashAttnVarlenFunc version？

### ISSUE THREAD

**Issue by Jayce1kk** [zhuzilin/ring-flash-attention#14]
Hello ! Megtron uses flash_attn_varlen_func function,have you ever written flash_attn_varlen_func version

**Comment by zhuzilin** [comment]
It should be very similar to `flash_attn_varlen_qkvpacked_func`, the only difference is that the currently implementation does not support `cu_seqlens_q != cu_seqlens_k` which should not happen during training.

**Comment by Jayce1kk** [comment]
Thank you for your reply. I have one more question to ask. For some jobs that use flash attention, can I replace the flash attention function with the corresponding function in ring flash attention?

**Comment by zhuzilin** [comment]
When substituting flash attn with ring attn, you need to adjust your dataloader, as all rank within the ring attn group need to share the same sequence of data (with different part of it). So if you are running with data parallel, you may need some extra modification with your code.

**Comment by zhuzilin** [comment]
btw, I implemented the `ring_flash_attn_varlen_func` just now. but it's a bit slow, so use the non-varlen version if possible~
