### ISSUE TITLE
test on 8*A800

### ISSUE THREAD

**Issue by JiaoPL** [zhuzilin/ring-flash-attention#18]
I tested on the 8*A800 machine, and below are my test results. 

flash_attn_qkvpacked_func : 464.177 iter/s, 0.215 sec
ring_flash_attn_qkvpacked_func: 28.712 iter/s, 3.483 sec
zigzag_ring_flash_attn_qkvpacked_func: 36.878 iter/s, 2.712 sec
stripe_flash_attn_qkvpacked_func: 37.264 iter/s, 2.684 sec

Compared to the A100 performance in the readme, `zigzag` only achieves 63.5% of the original flash_attn performance. Is this result reasonable?

**Comment by zhuzilin** [comment]
could you check if your node has nvlink?

**Comment by JiaoPL** [comment]
> could you check if your node has nvlink?

yeah, the node has nvlink,  and dist uses NCCL as backend.

**Comment by zhuzilin** [comment]
hmm... If all env vars are set correctly, then probably the performance difference between A100 and A800 is that A800 has slower nvlink bandwidth...(which shouldn't result in such performance degradation, as A800 and H800 has the same nvlink bandwidth).
