### ISSUE TITLE
关于tp和分块操作最终聚合的问题

### ISSUE THREAD

**Issue by Jayce1kk** [zhuzilin/ring-flash-attention#19]
作者您好，我尝试将您的代码集成到Megatron-LM上，使用的时候设置了tensor parallelism，同时代码中还对q,k,v进行了分块（local_q）,请问最终应该怎么聚合呢

**Comment by zhuzilin** [comment]
ring attn 的并行应该放在 dp 里面，和 tp 是相互不干扰的：tp_rank=0 的 ring_attn_size 张卡一组，tp_rank=1 的 ring_attn_size 张卡一组，以此类推。
