### ISSUE TITLE
Question about updating lse

### ISSUE THREAD

**Issue by jaesuny** [zhuzilin/ring-flash-attention#20]
Thank you for the excellent work.

Could you explain line 19 in the function?

I think it shoud be `new_lse = lse + block_lse`
Is there any analytic or numerical reason?

https://github.com/zhuzilin/ring-flash-attention/blob/78959746e8ce88394ded9263b417ec4708f3cc45/ring_flash_attn/utils.py#L9-L24

**Comment by zhuzilin** [comment]
As `lse = log(sum_a)` and `block_lse = log(sum_b)`, adding those two won't give us `log(sum_a + sum_b)`.

**Comment by jaesuny** [comment]
Thanks for the clear explanation!
