### ISSUE TITLE
flash attention版本

### ISSUE THREAD

**Issue by hxdtest** [zhuzilin/ring-flash-attention#21]
请问最低的flash-attention版本是？

**Comment by zhuzilin** [comment]
这个我没有仔细测过，应该 2.4.x 以上肯定是能跑的

**Comment by void-main** [comment]
如果要使用llama3的方案，至少需要 2.6.0 （支持unpadded lse），参考这个commit：https://github.com/Dao-AILab/flash-attention/commit/f816dee63c90e51c739baf0a27a450ee897632a8

**Comment by zhuzilin** [comment]
@void-main 我刚刚测试了一下，flash_attn 2.5.9 也就是老版本的 lse，和最新的 flash_attn，都是可以正确运行 `test_zigzag_ring_flash_attn_varlen_func.py` 的...

**Comment by void-main** [comment]
而且是GQA场景下，例如num_heads=64，num_kv_heads=8，这时候如果head_k_stride==1，就会挂

**Comment by zhuzilin** [comment]
> 啊，可能没说清楚，我这里跑的是llama3那个

奥奥，好的~ llama3 那个因为是新写的，所以确实没写老版本 flash attn 的兼容.... 我去加一下~

**Comment by zhuzilin** [comment]
@void-main 已经修了，可以 pull 一下最新的代码试试~

**Comment by void-main** [comment]
@zhuzilin 基于FA v2.4.2测试能过，谢谢大佬 👍
