### ISSUE TITLE
精度问题

### ISSUE THREAD

**Issue by hxdtest** [zhuzilin/ring-flash-attention#22]
There are some arithmetic errors with the current implementation. The reason for them is probably that flash attention will return bf16 value for each block, so we cannot accumluate the values with the original fp32 ones.

如果使用bf16精度，不是fp32精度，就不存在`accumluate the values with the original fp32 ones.` ?

**Comment by microhu** [comment]
> There are some arithmetic errors with the current implementation. The reason for them is probably that flash attention will return bf16 value for each block, so we cannot accumluate the values with the original fp32 ones.
> 
> 如果使用bf16精度，不是fp32精度，就不存在`accumluate the values with the original fp32 ones.` ?

这个问题有解法吗？ 我这边还真碰到了

**Comment by HaoshengZou** [comment]
@zhuzilin Is this partially solved? How? By llama3 implementation?

**Comment by zhuzilin** [comment]
flash attn does jot support fp32 or just returning fp32 tensors. The llama3 impl does have lower arithmetic error but still has it when calculating backward.
