### ISSUE TITLE
是否需要更新全局最大值？

### ISSUE THREAD

**Issue by ljliu** [zhuzilin/ring-flash-attention#31]
拜读了您的代码，有点小疑问：
从代码中看，调用flash attn算子只是完成了当前block的attn计算，其中的max是局部的，在后面的update_out_and_lse函数中也没有看到使用全局max更新的逻辑，是否是有问题？
https://github.com/lhao499/RingAttention/blob/90e920affeb634188b8a6fc491608164e1c135b3/bpt/ring_attention.py#L96 中有根据pre_max_score进行计算的逻辑。

**Comment by zhuzilin** [comment]
不会有问题，因为全局最大值的更新和 lse 的更新是一样的。

**Comment by chenlidar** [comment]
感觉不太对？flashattention2返回的lse是$m+log(l)$，是包含了当前block中的最大score的。如果能不保留最大值，那flashattention2的中间计算就也不必要保留max，而只用保留lse整体
