### ISSUE TITLE
Does ring-attn not support dropout?

### ISSUE THREAD

**Issue by chinapanda** [zhuzilin/ring-flash-attention#36]
In the backward function of ring-attn, rng_state does not use the value from forward function, but directly passes in None. 
Does this indicate that ring-attn does not support dropout?

**Comment by zhuzilin** [comment]
Good catch! yeah, I think it's hard to support dropout with the current implementation...

**Comment by chinapanda** [comment]
咱们有没有研究过te中的cp并行呢？这块是支持dropout的。这块逻辑是否可借鉴呢？
http://gitlab.software.cambricon.com/neuware/oss/nvidia/TransformerEngine/-/blob/v1.4.0_mlu/transformer_engine/pytorch/attention.py#L884-891
