### ISSUE TITLE
多卡qkv维度问题

### ISSUE THREAD

**Issue by kakaxi-liu** [zhuzilin/ring-flash-attention#37]
您好，多卡多batch微调qwen模型时，将sequence切分到不同卡上，由于存在attention mask，最后一张卡上的qkv的维度会和其它卡上不对应，最后导致nccl通信超时，针对这种情况应该怎么修改？

**Comment by zhuzilin** [comment]
> 最后一张卡上的qkv的维度会和其它卡上不对应

应该需要 padding 整个 sequence 到能被 ring size 整除，这样每张卡上的维度就一样了~

**Comment by kakaxi-liu** [comment]
> > 最后一张卡上的qkv的维度会和其它卡上不对应
> 
> 应该需要 padding 整个 sequence 到能被 ring size 整除，这样每张卡上的维度就一样了~

抱歉这么久才回复。假设我训练Sequence长度为4096，8卡训练，每张卡上batch是2，所以每张卡初始input是[2, 512]，正常来说在做attention之前qkv的维度应该是[2 * 512, head_nums, head_dims]，但是由于是batch训练在做flashattention前会通过attention mask做unpad操作，一般会导致qkv的维度变化（例如最后一张卡上qkv维度为[666, head_nums, head_dims]），这样在训练时会出现我上述提到的error。您理解我说的这种情况吗？
