### ISSUE TITLE
ring attention实现原理

### ISSUE THREAD

**Issue by lhcezx** [zhuzilin/ring-flash-attention#38]
ring attention本质是flash attention的分布式版本，flash attentionV2里面会维护softmax分母但是在更新out的时候好像只会更新最大值不会更新分母用于减少计算吧？在Q和一圈KV算完了以后最后除以一个softmax的global分母就可以了，所以作者这个ring attention实现的分布式FA可以理解成是v1版本的FA吗？

**Comment by zhuzilin** [comment]
抱歉可能是我对 FA 理解的有问题... 想问一下，如果不分段更新分母，如何得到 global 分母呢？

**Comment by lhcezx** [comment]
> 抱歉可能是我对 FA 理解的有问题... 想问一下，如果不分段更新分母，如何得到 global 分母呢？

公司电脑好像不能贴图片，可能我没有表述清楚。我想说的是分段更新分母是必要的，也就是对应update中的LSE更新吧，但是在计算out的时候每一次都需要将前一轮算出来的分母先 “消掉”，然后再 “除以“ 新算出来的分母用于得到当前的out。整个迭代过程对每块attn的结果就是在不断的更新它的分母，那么我们实际上不需要在循环过程中计算out的时候除以softmax分母，而是等待循环结束后我们得到维护好的最终global分母再除一下就可以了，不知道有没有表述清楚。过会我可以用markdown写一下应该也可以

**Comment by zhuzilin** [comment]
嗯... 我理解您是说，我们只需要在循环中叠加分子的部分，并存储分母的部分，到最后再用叠加起来的分子除以分母就行了。

然后现在的实现大致是这样的想法：现在每一段算出来的 block_out 是这一段的 分子 / 分母，因为 exp 太大了，我们不能直接把它恢复成分子，所以为了不用一直存储 block_out，我们需要把 block_out 和之前的 out，即 旧分子 / 旧分母 合并。所以就需要把 block_out 与 out 的分母都转成正确的 新分母，即 分母 + 旧分母。

这也是为什么现在的实现里面，每一轮都更新了分母。

**Comment by lhcezx** [comment]
> 嗯... 我理解您是说，我们只需要在循环中叠加分子的部分，并存储分母的部分，到最后再用叠加起来的分子除以分母就行了。
> 
> 然后现在的实现大致是这样的想法：现在每一段算出来的 block_out 是这一段的 分子 / 分母，因为 exp 太大了，我们不能直接把它恢复成分子，所以为了不用一直存储 block_out，我们需要把 block_out 和之前的 out，即 旧分子 / 旧分母 合并。所以就需要把 block_out 与 out 的分母都转成正确的 新分母，即 分母 + 旧分母。
> 
> 这也是为什么现在的实现里面，每一轮都更新了分母。

明白，我其实还有个别点理解的不是很透彻想请教一下作者。

**Comment by zhuzilin** [comment]
不用这么客气哈~

然后这里主要是 flash_attn 返回的 `lse` 是纯粹的 `log(B)`，并没有减去最大值。

**Comment by lhcezx** [comment]
> 不用这么客气哈~
> 
> 然后这里主要是 flash_attn 返回的 `lse` 是纯粹的 `log(B)`，并没有减去最大值。

哦？所以说_flash_attn_forward这个位于flash_attn库中函数返回的out里面的分子是有减掉最大值的（还是说分子也没有减掉最大值）？返回的lse是纯粹lse吗？

**Comment by zhuzilin** [comment]
out 是分子除分母的结果，从外面看减没减影响不大，但是估计里面的实现是减最大值实现的。然后 lse 是纯粹的 lse。

**Comment by lhcezx** [comment]
> out 是分子除分母的结果，从外面看减没减影响不大，但是估计里面的实现是减最大值实现的。然后 lse 是纯粹的 lse。

总感觉哪里有点问题，这是更新out的代码out = torch.exp(lse - new_lse) * out + torch.exp(block_lse - new_lse) * block_out；如果lse没有减掉最大值的话，那么上述的out的更新公式中的分母（lse）也是没有减掉最大值的，这样的话计算结果应该是不对的？

**Comment by snippetzero** [comment]
> > out 是分子除分母的结果，从外面看减没减影响不大，但是估计里面的实现是减最大值实现的。然后 lse 是纯粹的 lse。
> 
> 总感觉哪里有点问题，这是更新out的代码out = torch.exp(lse - new_lse) * out + torch.exp(block_lse - new_lse) * block_out；如果lse没有减掉最大值的话，那么上述的out的更新公式中的分母（lse）也是没有减掉最大值的，这样的话计算结果应该是不对的？

flash_attn 中的lse 应该是已经减去了最大值，可以参考其中triton版本的实现 https://github.com/Dao-AILab/flash-attention/blob/9486635c926ad1443c5c536d90e9cefaee3db9b4/flash_attn/flash_attn_triton.py#L215

**Comment by NonvolatileMemory** [comment]
大佬能解析下为什么backward只需要修正lse就可以了嘛

**Comment by wyooyw** [comment]
> > out 是分子除分母的结果，从外面看减没减影响不大，但是估计里面的实现是减最大值实现的。然后 lse 是纯粹的 lse。
> 
> 总感觉哪里有点问题，这是更新out的代码out = torch.exp(lse - new_lse) * out + torch.exp(block_lse - new_lse) * block_out；如果lse没有减掉最大值的话，那么上述的out的更新公式中的分母（lse）也是没有减掉最大值的，这样的话计算结果应该是不对的？

我也有类似的疑惑

**Comment by wyooyw** [comment]
> > > out 是分子除分母的结果，从外面看减没减影响不大，但是估计里面的实现是减最大值实现的。然后 lse 是纯粹的 lse。
> > 
> > 
> > 总感觉哪里有点问题，这是更新out的代码out = torch.exp(lse - new_lse) * out + torch.exp(block_lse - new_lse) * block_out；如果lse没有减掉最大值的话，那么上述的out的更新公式中的分母（lse）也是没有减掉最大值的，这样的话计算结果应该是不对的？
> 
> 我也有类似的疑惑

没事了，我理解了。
flash_attention计算block_out的时候，分子分母的指数位置减掉最大值，只是为了数值稳定，数学上不改变block_out的值。
所以，从外部来看，我们可以假定flash_attn分子分母没有减掉最大值，数学上是等价的。
所以在更新公式out = torch.exp(lse - new_lse) * out + torch.exp(block_lse - new_lse) * block_out里，lse不剪去最大值，数学上也是等价的。

**Comment by lhcezx** [comment]
> > > > out 是分子除分母的结果，从外面看减没减影响不大，但是估计里面的实现是减最大值实现的。然后 lse 是纯粹的 lse。
> > > 
> > > 
> > > 总感觉哪里有点问题，这是更新out的代码out = torch.exp(lse - new_lse) * out + torch.exp(block_lse - new_lse) * block_out；如果lse没有减掉最大值的话，那么上述的out的更新公式中的分母（lse）也是没有减掉最大值的，这样的话计算结果应该是不对的？
> > 
> > 
> > 我也有类似的疑惑
> 
> 没事了，我理解了。 flash_attention计算block_out的时候，分子分母的指数位置减掉最大值，只是为了数值稳定，数学上不改变block_out的值。 所以，从外部来看，我们可以假定flash_attn分子分母都没有减掉最大值，数学上是等价的。 所以，在更新公式out = torch.exp(lse - new_lse) * out + torch.exp(block_lse - new_lse) * block_out里，lse/new_lse/block_lse没有减最大值，而out/block_out等价于分子分母都没减最大值，所以数学上没问题。

数学上应该确实是没问题的，换句话说就是算子内部计算的时候应该做了最大值优化，但是ring attention外部的更新算子由于用的是未减去最大值的lse所以外部是没做最大值优化的。但是我个人理解哈如果lse里面实际上每个值都未减去rowmax，会导致lse的结果非常大如果用fp16跑推理的话很大概率数值会溢出？那么用lse是否是一个相对妥协的方法呢？
