### ISSUE TITLE
[咨询]请问 varlen 版本的 ring attention 有办法解除每个子序列都必须要被 degree 整除这个限制？

### ISSUE THREAD

**Issue by hhaAndroid** [zhuzilin/ring-flash-attention#51]
如题。上述限制对代码要求比较高，需要对每个子序列进行精细控制，而且会引入 padding 操作，请问是否有办法解除这个限制？

**Comment by hhaAndroid** [comment]
然后我看到 https://github.com/zhuzilin/ring-flash-attention/issues/17 里面提到 varlen 版本会慢很多，请问慢的如此多的主要原因是啥？谢谢

**Comment by zhuzilin** [comment]
@hhaAndroid 建议改成用 `llama3_flash_attn_varlen_func`

然后具体解释见：https://zhuanlan.zhihu.com/p/718486708
