### ISSUE TITLE
Will llama3_flash_attn suffer from the imbalance issue, too?

### ISSUE THREAD

**Issue by GeneZC** [zhuzilin/ring-flash-attention#52]
If so, how could we come up with a solution to this awkward situation similar to the zigzag idea?

**Comment by zhuzilin** [comment]
hmm... the zigzag idea is not imbalanced. And the llama3 version is imbalanced. And the reason for the llama3 version is for better varlen perf in larger cluster.

**Comment by GeneZC** [comment]
hhh i mean imbalance issue similar to ring attention and balanced solution similar to zigzag idea. anyway, thanks for your reply~
