### ISSUE TITLE
Thanks for your great work and here is my test results!

### ISSUE THREAD

**Issue by ChawDoe** [zhuzilin/ring-flash-attention#8]
I ran the test script on my single node machine, where I saw the memory cost of each attention: 
```
    benchmark_forward(flash_attn_qkvpacked_func) # 2k. gpu memory
    benchmark_forward(ring_flash_attn_qkvpacked_func) # 4k8. gpu memory
    benchmark_forward(ring_flash_attn_qkvpacked_func_v2) # 14k. gpu memory
    benchmark_forward(zigzag_ring_flash_attn_qkvpacked_func) # 5k. gpu memory
```
And the running time of each attention: 
```
flash_attn_qkvpacked_func 4470.3194011016185 iter/s, 0.22369766235351562 sec
ring_flash_attn_qkvpacked_func 327.3293995259765 iter/s, 3.0550265312194824 sec
ring_flash_attn_qkvpacked_func_v2 310.57613547187344 iter/s, 3.219822406768799 sec
zigzag_ring_flash_attn_qkvpacked_func 340.40177158407965 iter/s, 2.9377050399780273 sec
```
Is there something wrong?

**Comment by zhuzilin** [comment]
the speed is correct, as the ring versions are doing 8 times more calculation than the native flash attn version (8 * 1 * 1 vs 1 * 8 * 8), so it should be at least 8 times slower. Now it's 13 time slowers, so there should be some room for improvement, but I'm not sure how much are there, because we has to do some copies (`to(torch.bf16)`, `to(torch.fp32)`).

I'll check for the memory usage... 2x memory usage is probably the limit, because we need to do double buffer for the communication.

**Comment by zhuzilin** [comment]
btw, could you share what GPU are you using and if they have nvlink connected? the ring attention does a lot of inter-gpu communication, so a fast interconnection is needed.

**Comment by zhuzilin** [comment]
@ChawDoe We just improved the kernel performance and made the benchmark a bit larger (the origin one is too small to ignore kernel launch time). The current performance is:

<img width="911" alt="image" src="https://github.com/zhuzilin/ring-flash-attention/assets/10428324/6a13f0d5-da49-4766-8df0-daaa417b788b">

which makes the ring kernel close the theoretic speed.

**Comment by foreverpiano** [comment]
on my current 8*A100 1node
flash_attn_varlen_qkvpacked_func 637.3449975040498 iter/s, 0.15690089416503905 sec                            
ring_flash_attn_varlen_qkvpacked_func 17.99685353838967 iter/s, 5.55652685546875 sec
still slower than 8x

**Comment by zhuzilin** [comment]
@foreverpiano 
the varlen version is slow, because it requies too much copied, we may need to write some triton kernel for that...
could you give the the non-varlen version a test?

**Comment by foreverpiano** [comment]
453.599 iter/s, 0.220 sec
17.332 iter/s, 5.770 sec
is there anything missing? @zhuzilin

**Comment by zhuzilin** [comment]
@foreverpiano just run the benchmark with an A100 node, the result is:
```
# flash_attn_qkvpacked_func
471.527 iter/s, 0.212 sec
# ring_flash_attn_qkvpacked_func
33.347 iter/s, 2.999 sec
# zigzag_ring_flash_attn_qkvpacked_func
49.641 iter/s, 2.014 sec
# stripe_flash_attn_qkvpacked_func
45.937 iter/s, 2.177 sec
```

Could you check if your node has nvlink connection between GPUs? If not, the slow interconnection may greatly slow down ring attn.

**Comment by LzhinFdu** [comment]
> the speed is correct, as the ring versions are doing 8 times more calculation than the native flash attn version (8 * 1 * 1 vs 1 * 8 * 8), so it should be at least 8 times slower. Now it's 13 time slowers, so there should be some room for improvement, but I'm not sure how much are there, because we have to do some copies (`to(torch.bf16)`, `to(torch.fp32)`).
> 
> I'll check for the memory usage... 2x memory usage is probably the limit, because we need to do double buffer for the communication.

“the ring versions are doing 8 times more calculation”
I'm sorry I don't understand the meaning here. Does this mean that under the same input, ring attention requires more calculations, resulting in increased time consumption, or does it mean that ring attention processes more samples during the test, resulting in increased time consumption?
